#!/bin/bash

# Ryan Linden
# CSE 374
# HW2 Part 3

# Make sure at least 2 arguments input
if [[ $# -lt 2 ]]
then
  echo "${0}: need at least 2 arguments: combine [destination-file] [source-file]" >&2
  exit 1
fi

# Check if destination file already exists
if [ -a $1 ]
then
  echo "Error: first file exists">&2
  exit 1
fi

# Get destination and source file names
destFile=$1

string=''
shift
for file in "$@"
do
  if [ ! -a $file ]
  then
    echo "Error $file : no such file found" >> $destFile
  fi
  string="$string$file"
done
echo $string
