#!/bin/bash

# Ryan Linden
# CSE 374
# HW2 Part4

# Make sure there are at least two arguments, one destination file and one source file
if [ $# -lt 2 ]
then
  echo "${0}: Error: needs at least two arguments">&2
  exit 1
fi

# Set parameters
destFile=${1} # Destination file to append
totalArgs=$# # Total arguments input to command
totalLines=0 # Total lines to be counted in files

date >> $destFile # Add date/time to destination file

# Count lines in files and add counts to destination file, while also keeping a total sum
shift
for file in $@
do
  lineCount=$(wc -l $file | awk '{print $1;}')
  ((totalLines="$totalLines+$lineCount"))
  echo "$lineCount $file" >> $destFile
done

# If two or more files to be counted, output a total line number to destination file
if [ $totalArgs -ge 3 ]
then
   echo "$totalLines total" >> $destFile
fi
